version: "3.9"
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=meeting_db
      - DB_USER=root
      - DB_PASSWORD=root

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:80"  # Vite dev 或 nginx prod

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meeting_db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
